### ISSUE TITLE
Support for Next 13/React 18?

### ISSUE THREAD

**Issue by zargold** [danielr18/connected-next-router#100]
Does this work with React 18, Next 13 maybe with the app directory?

**Comment by danielr18** [comment]
@zargold There's no support for app directory yet.

I released `connected-next-router@5.0.0-rc.1` today, which supports Next 13, React 18, and next-redux-wrapper 8.
https://github.com/danielr18/connected-next-router/pull/102

**Comment by felschr** [comment]
`5.0.0-rc.1` contains `@types/react-redux` in the normal `dependencies`, which might cause conflicts since `react-redux@8.0.0` now comes with its own types.

I'm actually not sure how it ended up there, since I can't find it in the `package.json` of the source, but this from my local `node_modules/connectec-next-router/package.json`:
```json
  "dependencies": {
    "@types/react-redux": "^7.1.27"
  }
```

Update: It does seem to prefer the types from `react-redux`, in my editor at least. Still, this package shouldn't be in `dependencies`, but at least it doesn't seem to break anything.

**Comment by danielr18** [comment]
Good catch @felschr, thanks!
It probably got there by one of the Snyk PRs. I'll take care of it before releasing the new version.

**Comment by felschr** [comment]
You're probably aware already, but Next.js 14 has also recently been released.

**Comment by danielr18** [comment]
Version 5 has been released
