### ISSUE TITLE
Redirects to / on refresh

### ISSUE THREAD

**Issue by haf** [danielr18/connected-next-router#27]
If you apply connected-next-router - client-side only —

```ts
import React, { Component, ReactNode } from 'react'
import { Provider } from 'react-redux'
import { Store, applyMiddleware } from 'redux'
import { createRouterMiddleware, initialRouterState, ConnectedRouter } from 'connected-next-router'
import { createStore } from 'redux';
import { MakeStoreOptions } from 'next-redux-wrapper';
import { error } from '../lib/logary';
import { Router } from '../server/lib/routes';

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function createStub(_: Record<string, any>, __?: MakeStoreOptions) {
  const routerMiddleware = createRouterMiddleware({
    Router,
    methods: { push: 'pushRoute', replace: 'replaceRoute', prefetch: 'prefetchRoute' },
  })
  const enhancer = applyMiddleware(routerMiddleware)
  return createStore((s: any) => s, { router: initialRouterState() }, enhancer)
}

export default class ReduxApp extends Component<{ children: ReactNode }, { store: Store }> {
  constructor(props: any) {
    super(props)
    this.state = { store: createStub({}) }
    if (typeof window !== 'undefined') {
      import('./redux').then(
        x => this.setState({ store: x.create({}) }),
        err => error('Loading Redux failed', { error: err }))
    }
  }

  render() {
    return (
      <Provider store={this.state.store}>
        <ConnectedRouter>
          {this.props.children}
        </ConnectedRouter>
      </Provider>
    )
  }
}

// export default withRedux(storeCallback)(ReduxApp)
```

- and you always add the above component to your tree - and then go to an arbitrary non-root page and refresh the browser - then connected-next-router will navigate the browser to `/` and then back to e.g. `/blog`. :( NOT always, however; only once in a while. Here's a screenshot of the bug in action;

<img width="912" alt="image" src="https://user-images.githubusercontent.com/193115/62837058-1583ea00-bc6b-11e9-9808-f8bf199ef523.png">

This causes redirect flows with oauth2 to fail.

**Comment by vincegio** [comment]
Getting this too, did you manage to solve this issue?

**Comment by haf** [comment]
Yes, it's a race condition between the polling/fetching of the current state as performed by this module and the change of the location; I completely dropped this project and am now using the `req` and `ctx` values from nextjs and the window.location to get the location, rather than this project.

**Comment by vincegio** [comment]
Yeah I ended up doing the same, _query_ and _asPath_ are the ones I use the most.

**Comment by danielr18** [comment]
I've been trying to recreate, but I can't even get the app to work with something like this:

```
class ExampleApp extends App {
  constructor(props) {
    super(props)
    this.state = { store: createStub() }
  }
  componentDidMount() {
    this.setState({ store: this.props.store });
  }

  render() {
    const { Component, pageProps } = this.props
    return (
      <Container>
        <Provider store={this.state.store}>
          <ConnectedRouter>
            <Component {...pageProps} />
          </ConnectedRouter>
        </Provider>
      </Container>
    )
  }
}

export default withRedux(configureStore)(ExampleApp)
```

Stuck at home page every time I try to nagivate.

@haf Would this issue be avoided if url is passed to initialRouterState in the stub? Otherwise it will be '/' by default.

**Comment by haf** [comment]
@danielr18 Yes, potentially. The trick is probably to be very sure to synchronise the state between window.location, next and redux very closely, and if you know what path you're at, it's best to use it (and you do know server-side what path you're at when you create the store)

**Comment by joaovieira** [comment]
I think I'm bumping into something similar. 

I've noticed Next.js doesn't necessarily call `routeChangeComplete` before another `routeChangeStart`. This means you can have two ongoing routes changes at the same time. Given this package only uses a single boolean for `isTimeTravelEnabled`, it can get caught into a race condition. E.g.

1. Current href: `/a`;
2. User navigates to url `/b`. That triggers the first `routeChangeStart` and disables "time travelling";
3. Page `/b` updates url with query params on mount. I.e. replaces url with `/b?foo=bar`. This triggers a second `routeChangeStart` before the first one finished;
4. First route finishes, `routeChangeComplete` is emitted, which enables "time travelling" again;
5. Given the router changed (url is now `/b?foo=bar`), the url is not the same as the one in store (`/a`) and "time travelling" is enabled (even though there's still an ongoing route change - the second was not completed), the connected router dispatches an update to change the url to the one in the store (i.e. `/a`) - https://github.com/danielr18/connected-next-router/blob/master/src/ConnectedRouter.js#L95
6. This ends up reverting the user back to `/a`, rather than the expected url - `/b?foo=bar`

Using a counter to enable/disable "time travelling" rather than a boolean would fix it.

**Comment by danielr18** [comment]
@joaovieira The fix has been released on v3
